### ISSUE TITLE
Firmware and other files

### ISSUE THREAD

**Issue by tripflex** [ajfoul/MOD-t#1]
Hey thanks for all the details on here, I was going to fork yours but wanted to setup a directory structure and add firmware files, etc .. just wanted to let you know:

https://github.com/tripflex/MOD-t

Thanks again!

**Comment by ajfoul** [comment]
Bummer! I like getting forked :-) One of these days I might even get a pull req...
Post your repo to the Google group please: https://groups.google.com/forum/?#!forum/mod-t
